#!/usr/bin/env python3

import sys

from rqt_acquisition.vio_module import VioPlugin
from rqt_gui.main import Main

plugin = 'rqt_vioacq'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
